### ISSUE TITLE
K线显示异常

### ISSUE THREAD

**Issue by LiuGanQQQ** [OpenFlutter/k_chart#1]
KLineEntity类的change和ratio属性没有赋值,vol用的amount的值.
不知道是不是和这个有关系,请楼主赐教哈~
![1578992299494](https://user-images.githubusercontent.com/21186780/72329988-b67e4180-36f0-11ea-8ba8-9b4e0813b121.jpg)
![123](https://user-images.githubusercontent.com/21186780/72329991-b716d800-36f0-11ea-979b-d7ec1604491c.jpg)

**Comment by mafanwei** [comment]
change和ratio不赋值会自动计算，demo的api用的不对，属于特殊处理。

**Comment by mafanwei** [comment]
建议你打印一下数据，看看边界的数据发生了什么

**Comment by LiuGanQQQ** [comment]
> 建议你打印一下数据，看看边界的数据发生了什么

好的,我打印下数据哈

**Comment by LiuGanQQQ** [comment]
> 建议你打印一下数据，看看边界的数据发生了什么

感谢,确实是数据时间顺序错了,开盘价为0,特殊处理下数据就好了,谢谢
