### ISSUE TITLE
Flutter candlestick chart - request 

### ISSUE THREAD

**Issue by varun2india89** [OpenFlutter/k_chart#13]
我已经检查了您的flutter库，这是一项了不起的工作。 我需要对现有flutter项目进行一些自定义和添加。 你能做到吗 ？ 我该如何联系您？

**Comment by mafanwei** [comment]
由于工作原因，我暂时不会使用flutter，但是仍欢迎pr，期待你的提交

**Comment by mafanwei** [comment]
没有回复，关闭
