### ISSUE TITLE
希望你注明是在https://github.com/gwhcn/flutter_k_chart源码上改的

### ISSUE THREAD

**Issue by gwhcn** [OpenFlutter/k_chart#17]
有部分人用的你这边代码，跑到我群里提bug。

**Comment by nb312** [comment]
别人的代码 贴二维码 过分了啊

**Comment by mafanwei** [comment]
功能应该差距挺大的，你的项目计算基本都是错的。但因为本人从那家公司离职，所以不怎么维护了，可能有机会的话，会用flutter2重写一下。

**Comment by mafanwei** [comment]
如果仅改一点的话，我会选择fork并提交pr。

**Comment by mafanwei** [comment]
如果你有维护意愿话，此项目可以转让于你，如果你希望的加上thanks的话，我也可以加，但是我属实不知道90%结论从哪来的。

**Comment by mafanwei** [comment]
好的
