### ISSUE TITLE
Add ticker support

### ISSUE THREAD

**Issue by 5eeman** [OpenFlutter/k_chart#18]
Hi,
Maybe I haven't found, but is there ability to add support of live ticker like in example attached below(yellow price at the right).
![2021-04-02 13 36 05](https://user-images.githubusercontent.com/13124808/113408681-75875100-93b8-11eb-9c79-d4547cbad860.jpg)

**Comment by mafanwei** [comment]
Will do

**Comment by mafanwei** [comment]
Added. 
Please use latest to test.
If there are problems, please give feedback.

**Comment by 5eeman** [comment]
Thanks, that was really helpful)
