### ISSUE TITLE
simple kline/candle chart for k_chart.

### ISSUE THREAD

**Issue by bsjung** [OpenFlutter/k_chart#2]
I've found it's very good for my project.

But, there do not exist for the basic kline/candle chart.
Anyway, I've tried for a simple chart with k_chart.

Thanks.

Benjamin Jung ( bsjung@gmail.com )

**Comment by mafanwei** [comment]
Thank you for topic.
But work is too busy.
I'm afraid I haven't had enough time to do this recently.
Can you share your code?
pr is welcome.

**Comment by bsjung** [comment]
I've made k_chart examples in my GitHub.

https://github.com/bsjung/k_chart_examples.

**Comment by mafanwei** [comment]
see issue #4
