### ISSUE TITLE
Need some space on edges

### ISSUE THREAD

**Issue by mdat31** [OpenFlutter/k_chart#25]
Hi! Can you add some space on the start edge and end egde of the chart like this, a parameter for it would be perfect.

![image](https://user-images.githubusercontent.com/57827919/120745789-1238ad00-c528-11eb-9c04-e698e05ce5bc.png)

**Comment by mafanwei** [comment]
No plans to do this recently, you can do it yourself.

**Comment by steebchen** [comment]
I agree with OP that this would be nice to configure. If you display the widget to 100% since you want the graph to touch the screen edges, you don't want the values (both vertical and horizontal) to do that, rather they should have a configurable padding.

**Comment by mafanwei** [comment]
Link #59
