### ISSUE TITLE
ability to change grid colors

### ISSUE THREAD

**Issue by bkmio** [OpenFlutter/k_chart#26]
I'm trying to switch from default dark theme to light theme (white background) and I'm trying to change the grid colors.

I found in base_chart_renderer.dart line 16 the gridPaint is a fixed color of 0xff4c5c74.

```
    ..color = Colors.red;
  Paint gridPaint = Paint()
    ..isAntiAlias = true
    ..filterQuality = FilterQuality.high
    ..strokeWidth = 0.5
    ..color = Color(0xff4c5c74); <-----
```
    
    Could you extend the capability to allowing custom colors via chart_style.dart please?
    
    Thanks!

**Comment by mafanwei** [comment]
Will do.
Thank you.

**Comment by mafanwei** [comment]
Done. Use 0.3.1.
