### ISSUE TITLE
Zoom in/out with touch and drag the yaxis (like TradingView)

### ISSUE THREAD

**Issue by coditori** [OpenFlutter/k_chart#27]
Please take a look at TradingView chart it's a cool feature to have zoom

**Comment by mafanwei** [comment]
Why need y zoom in/out?

**Comment by coditori** [comment]
Because in the mobile application screen is going to be easier to do the zoom with one finger rather than two ones.

**Comment by mafanwei** [comment]
I've seen it and I'm afraid I don't have time for this. I would be happy if someone could help me.
