### ISSUE TITLE
有没有预留绘制实时数据的接口呢？

### ISSUE THREAD

**Issue by TransFormes** [OpenFlutter/k_chart#29]
和火币一样，实时有一条线在绘制

**Comment by mafanwei** [comment]
最新的一条线有个UI显示，不知道你要什么样的效果

**Comment by TransFormes** [comment]
![image](https://user-images.githubusercontent.com/31639628/122004189-acc9a380-cde6-11eb-8549-2e299433646c.png)

**Comment by mafanwei** [comment]
是k线图在最右侧才会有还是k线图在哪都会有？

**Comment by TransFormes** [comment]
最右侧

**Comment by mafanwei** [comment]
好，回头加上

**Comment by TransFormes** [comment]
flutter_k_chart 这个插件是有这个功能， 你去掉了吗

**Comment by TransFormes** [comment]
![image](https://user-images.githubusercontent.com/31639628/122152664-31263000-ce94-11eb-8ffb-e0dbe34b9f03.png)

**Comment by mafanwei** [comment]
此项目起步稍晚于flutter_k_chart，当初指望着fork然后pr，后由于一些原因，选择了另起炉灶，丢掉了100多次提交，显得
此项目首次提交很晚，实际双方更新的内容并不一致。

**Comment by mafanwei** [comment]
此项目不是flutter_k_chart的plus版本

**Comment by mafanwei** [comment]
此功能在0.2.0添加，在0.4.0大幅修改了样式。
