### ISSUE TITLE
i18n supports 

### ISSUE THREAD

**Issue by bsjung** [OpenFlutter/k_chart#3]
I think the i18n infoNames[] instead of infoNamesCN or infoNamesEN in k_chart_widget.dart.

------------------------------------------

  final List<String> infoNamesCN = [
    "时间",
    "开",
    "高",
    "低",
    "收",
    "涨跌额",
    "涨跌幅",
    "成交额"
  ];
  final List<String> infoNamesEN = [
    "Date",
    "Open",
    "High",
    "Low",
    "Close",
    "Change",
    "Change%",
    "Amount"
  ];

------------------------------------------

Anyway, I've tried to experiment with k_chart for my project.

1. https://github.com/bsjung/k_chart.
2. https://github.com/bsjung/start_examples.

**Comment by mafanwei** [comment]
For some reasons, I don’t want to import other libraries in my project.
