### ISSUE TITLE
how to use general line/pie charts with k_chart.

### ISSUE THREAD

**Issue by bsjung** [OpenFlutter/k_chart#4]
At first, I've tried integrating google charts with k_chart. But google charts has  complex architecture.
My intentions are an intuitive API for easy use. 

Thus, I've re-designed my packages for general line/pie charts with k_chart.
Still, it is an alpha stage, but I will notice if I've completed it.

Benjamin Jung ( bsjung@gmail.com )

**Comment by bsjung** [comment]
I've forked k_chart in https://github.com/bsjung/k_chart.git.
And I've re-designed start_chart in https://github.com/bsjung/start_chart.git.

There are start_examples with Start web framework ( https://github.com/bsjung/start_examples )
I've added chart example in start_examples.

**Comment by mafanwei** [comment]
Good job

**Comment by bsjung** [comment]
Thank you. It's alpha stage. But, I'll update k_chart if there are any progress.
