### ISSUE TITLE
Draw a Trendline

### ISSUE THREAD

**Issue by afzl-wtu** [OpenFlutter/k_chart#40]
Please can you add this functionality in the chart?
![WhatsApp-Video-2021-07-23-at-8 03 48-PM](https://user-images.githubusercontent.com/64379149/127302897-b4ae847c-afde-42d1-801e-2d9d4fdd8579.gif)

**Comment by mafanwei** [comment]
Will do

**Comment by afzl-wtu** [comment]
> Will do

I have already implemented it in my app. Line is working really fine. Tell me if I can help you.

**Comment by mafanwei** [comment]
I'm glad to accept PR.
Thank you.

**Comment by afzl-wtu** [comment]
> I'm glad to accept PR. Thank you.

It is just a simple line shown as below by clicking draw button and the long press on chart.

https://user-images.githubusercontent.com/64379149/147233988-63da4499-6c93-435a-999e-764e62d7aed4.mp4

**Comment by afzl-wtu** [comment]
PR soon.
