### ISSUE TITLE
我自己获取的数据不显示图表

### ISSUE THREAD

**Issue by yangzhenshan** [OpenFlutter/k_chart#45]
我自己的数据结构如下：
![issue](https://user-images.githubusercontent.com/18318443/137732526-414a7f2d-0a41-45b5-9273-258cb820baeb.png)

看上去似乎和火币的数据一致了，但是我不能显示图表，还有可能是什么原因呢

**Comment by mafanwei** [comment]
可以使用项目中的json解析
