### ISSUE TITLE
一开始不显示kline，要滚动页面再回来才会显示

### ISSUE THREAD

**Issue by yangzhenshan** [OpenFlutter/k_chart#50]
使用了DataUtil.calculate()方法，也用了setState方法，但是一开始都不显示kline，请问我的问题出在哪

![A681FE1CC232C8AA3E836E18170A7A31](https://user-images.githubusercontent.com/18318443/144802265-c8fb247f-5198-4ad3-9617-17c83b3c20b7.gif)
![WX20211206-150627](https://user-images.githubusercontent.com/18318443/144802493-0e296ad7-75e6-42f1-964c-677979626187.png)

**Comment by mafanwei** [comment]
建议异步set数据，并检查time是否正确

**Comment by yangzhenshan** [comment]
不好意思，是我自己状态管理的问题
