### ISSUE TITLE
Padding between grid Prices and Candles

### ISSUE THREAD

**Issue by radian-rgc** [OpenFlutter/k_chart#51]
How to make padding between grid prices and candles?

Like this:

![kline2](https://user-images.githubusercontent.com/23151404/146844059-3218b372-da0a-448d-854a-d9a4c1c04994.png)

**Comment by radian-rgc** [comment]
Just override below code

`double getX(int position) => position * mPointWidth + mPointWidth / 2`

to 

`double getX(int position) => (position * mPointWidth + mPointWidth / 2)-50`

in this file:

`base_chart_painter.dart`

**Comment by mafanwei** [comment]
Will do
