### ISSUE TITLE
Price labels alignment

### ISSUE THREAD

**Issue by constantinoschristoforou** [OpenFlutter/k_chart#57]
Is there a way to align the price labels the right?
![image](https://user-images.githubusercontent.com/10140784/154634864-2887030e-33ef-4cb2-8d88-79a87f3817a2.png)

**Comment by mafanwei** [comment]
Will do.

**Comment by mafanwei** [comment]
If you have time, you can also pull request.

**Comment by mafanwei** [comment]
use VerticalTextAlignment.
