### ISSUE TITLE
图挂啦

### ISSUE THREAD

**Issue by sunjianan9900** [OpenFlutter/k_chart#68]

**Comment by mafanwei** [comment]
指的什么？demo的图表在转圈？

**Comment by sunjianan9900** [comment]
README.md  我说的readme哈
在 pubdev.top 上看到的，因为没有图

**Comment by sunjianan9900** [comment]
![image](https://user-images.githubusercontent.com/10936316/196092437-65099a00-399b-4352-baf2-ecafbe4e0fb6.png)

**Comment by mafanwei** [comment]
不清楚，可能更新的时候图地址换了？

**Comment by mafanwei** [comment]
回头我重新传一下

**Comment by mafanwei** [comment]
修复了
