### ISSUE TITLE
Hi! I'm developing a few more properties and functions, so can I update this?

### ISSUE THREAD

**Issue by su-mong** [OpenFlutter/k_chart#73]
I'm a developer who is using the 'k_chart' library to make good use of it. I needed some functions, so I download k_chart project, and now, I'm  modifying some code to add these. I want to reflect these in the main library. Is there anything I should be careful about before requesting a pull request? 

The functions I added are as follows :
1. Adding property `infoDialog` on `KChartWidget` : Users can now apply custom UI to `infoDialog`.
2. Adding properties for Volume Chart bar color
3. Adding Chart bar radius property
4. Adding a property that selects whether or not to display a date

**Comment by mafanwei** [comment]
Nothing to attention, just do it.
