### ISSUE TITLE
kChart Loads Nota Sans font (7.5MB)

### ISSUE THREAD

**Issue by MisaGu** [OpenFlutter/k_chart#76]
### **The Problem**

I am working on the web app and I just found out that kChart always loads the Nota Sans font, which adds 7.5 MB of unnecessary data. The issue lies with the symbol ' ──' in the chart_painter.dart file, specifically in the drawMaxAndMin method.

```
TextPainter tp = getTextPainter(
          mMainLowMinValue.toStringAsFixed(fixedLength) + " ──",
          chartColors.minColor);
```

#### replace ' ──' with ' --' 

I also tried to replace it with "⎯" (U+23AF), which looks like the original line (⎯⎯), but it still causes the package to load the Nota font. The good thing is that the size was reduced to 94KB, but for me, it is still not acceptable as it is more than 0.

#### Stack:
Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19044.2846],
    locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\flutter_3+
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

Chrome (web) • chrome • web-javascript • Google Chrome 113.0.5672.93

**Comment by mafanwei** [comment]
You're awesome!
