### ISSUE TITLE
web端在移动Ios设备谷歌浏览器和Safari浏览器页面崩溃 无法绘制数据  data传空数组时页面正常显示

### ISSUE THREAD

**Issue by edison-fe-html** [OpenFlutter/k_chart#78]
class ExchangeView extends StatefulWidget {
  const ExchangeView({Key? key}) : super(key: key);

  @override
  State<ExchangeView> createState() => _ExchangeViewState();
}

class _ExchangeViewState extends State<ExchangeView> {
  final List exampleData = [
    {
      'id': 1685030400,
      'open': 26227.99,
      'close': 26435.09,
      'low': 26207.27,
      'high': 26629.2,
      'amount': 1832.5096671812694,
      'vol': 48418470.86422568,
      'count': 44053
    },
    {
      'id': 1684944000,
      'open': 26315.6,
      'close': 26224.28,
      'low': 25869.36,
      'high': 26487.02,
      'amount': 3285.3798137988733,
      'vol': 86284596.12235801,
      'count': 82497
    },
    {
      'id': 1684857600,
      'open': 27320,
      'close': 26312.32,
      'low': 26081.64,
      'high': 27340,
      'amount': 3484.8427698660767,
      'vol': 93218621.13446784,
      'count': 86322
    },
    {
      'id': 1684771200,
      'open': 26874.47,
      'close': 27318.49,
      'low': 26780.94,
      'high': 27491.99,
      'amount': 3056.4089958920886,
      'vol': 83036031.77142552,
      'count': 71385
    },
    {
      'id': 1684684800,
      'open': 26899.11,
      'close': 26874.48,
      'low': 26535,
      'high': 27086,
      'amount': 2971.442114456641,
      'vol': 79663068.28368054,
      'count': 73800
    },
    {
      'id': 1684598400,
      'open': 26948.88,
      'close': 26899.12,
      'low': 26786.83,
      'high': 27286.56,
      'amount': 1847.9179029555737,
      'vol': 49900344.77060829,
      'count': 50836
    },
    {
      'id': 1684512000,
      'open': 26885.01,
      'close': 26948.88,
      'low': 26785,
      'high': 26975,
      'amount': 1715.569257279128,
      'vol': 46113216.908862315,
      'count': 35384
    },
    {
      'id': 1684425600,
      'open': 27086.99,
      'close': 26885.01,
      'low': 26368.1,
      'high': 27178.69,
      'amount': 4443.294925983878,
      'vol': 119222610.84997982,
      'count': 92820
    },
    {
      'id': 1684339200,
      'open': 26797.89,
      'close': 27086.99,
      'low': 26746.17,
      'high': 27500,
      'amount': 3698.1189629584596,
      'vol': 100766035.6654233,
      'count': 94654
    },
    {
      'id': 1684252800,
      'open': 27040.49,
      'close': 26797.89,
      'low': 26555,
      'high': 27236,
      'amount': 3582.0041864038903,
      'vol': 96258379.83635026,
      'count': 83912
    }
  ];
  late List<KLineEntity> data = [];
  final ChartStyle chartStyle = ChartStyle();
  final ChartColors chartColors = ChartColors();
  final MainState mainState = MainState.MA;

  @override
  void initState() {
    super.initState();
    List<KLineEntity>? res = [];
    for (var item in exampleData) {
      res.add(KLineEntity.fromJson(item));
    }
    setState(() {
      data = res;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('K Line'),
        centerTitle: true,
      ),
      body: Container(
        width: 1080.w,
        height: 2400.h,
        color: Colors.white,
        child: KChartWidget(
          data,
          chartStyle,
          chartColors,
          isTrendLine: true,
          isTapShowInfoDialog: true,
          isLine: false,
          hideGrid: true,
          mainState: mainState,
        ),
      ),
    );
  }
}

**Comment by mafanwei** [comment]
使用assets里的json文件可以正常显示么

**Comment by edison-fe-html** [comment]
没有试过本地的json

**Comment by edison-fe-html** [comment]
你试下在web端在ios上的谷歌浏览器看看正常吗  我这边测试安卓手机是没问题的 就是ios手机有问题 我试了3种不同的ios设备  在每台ios设备上的谷歌浏览器和Safari浏览器上都不能正常绘制

**Comment by mafanwei** [comment]
不能绘制报什么错呢

**Comment by edison-fe-html** [comment]
不会报错 在网页上直接页面崩溃

**Comment by edison-fe-html** [comment]
https://github.com/OpenFlutter/k_chart/assets/71269406/d3b6fdab-0131-40af-9c75-6bbc53229ed3

**Comment by edison-fe-html** [comment]
控制台并没有显示错误日志

**Comment by edison-fe-html** [comment]
只要对data设置数据  就会页面异常  但是控制台并没有任何报错显示

**Comment by edison-fe-html** [comment]
在安卓设备上浏览器中运行正常

https://github.com/OpenFlutter/k_chart/assets/71269406/f28bcfa2-3bb8-4c9f-8cb4-7d3f67d320a1

**Comment by edison-fe-html** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'package:k_chart/chart_style.dart';
import 'package:k_chart/entity/k_line_entity.dart';
import 'package:k_chart/k_chart_widget.dart';

class ExchangeView extends StatefulWidget {
  const ExchangeView({Key? key}) : super(key: key);

  @override
  State<ExchangeView> createState() => _ExchangeViewState();
}

class _ExchangeViewState extends State<ExchangeView> {
  final List exampleData = [
    {
      'id': 1685030400,
      'open': 26227.99,
      'close': 26435.09,
      'low': 26207.27,
      'high': 26629.2,
      'amount': 1832.5096671812694,
      'vol': 48418470.86422568,
      'count': 44053
    },
    {
      'id': 1684944000,
      'open': 26315.6,
      'close': 26224.28,
      'low': 25869.36,
      'high': 26487.02,
      'amount': 3285.3798137988733,
      'vol': 86284596.12235801,
      'count': 82497
    },
    {
      'id': 1684857600,
      'open': 27320,
      'close': 26312.32,
      'low': 26081.64,
      'high': 27340,
      'amount': 3484.8427698660767,
      'vol': 93218621.13446784,
      'count': 86322
    },
    {
      'id': 1684771200,
      'open': 26874.47,
      'close': 27318.49,
      'low': 26780.94,
      'high': 27491.99,
      'amount': 3056.4089958920886,
      'vol': 83036031.77142552,
      'count': 71385
    },
    {
      'id': 1684684800,
      'open': 26899.11,
      'close': 26874.48,
      'low': 26535,
      'high': 27086,
      'amount': 2971.442114456641,
      'vol': 79663068.28368054,
      'count': 73800
    },
    {
      'id': 1684598400,
      'open': 26948.88,
      'close': 26899.12,
      'low': 26786.83,
      'high': 27286.56,
      'amount': 1847.9179029555737,
      'vol': 49900344.77060829,
      'count': 50836
    },
    {
      'id': 1684512000,
      'open': 26885.01,
      'close': 26948.88,
      'low': 26785,
      'high': 26975,
      'amount': 1715.569257279128,
      'vol': 46113216.908862315,
      'count': 35384
    },
    {
      'id': 1684425600,
      'open': 27086.99,
      'close': 26885.01,
      'low': 26368.1,
      'high': 27178.69,
      'amount': 4443.294925983878,
      'vol': 119222610.84997982,
      'count': 92820
    },
    {
      'id': 1684339200,
      'open': 26797.89,
      'close': 27086.99,
      'low': 26746.17,
      'high': 27500,
      'amount': 3698.1189629584596,
      'vol': 100766035.6654233,
      'count': 94654
    },
    {
      'id': 1684252800,
      'open': 27040.49,
      'close': 26797.89,
      'low': 26555,
      'high': 27236,
      'amount': 3582.0041864038903,
      'vol': 96258379.83635026,
      'count': 83912
    }
  ];
  late List<KLineEntity> data = [];
  final ChartStyle chartStyle = ChartStyle();
  final ChartColors chartColors = ChartColors();
  final MainState mainState = MainState.MA;

  @override
  void initState() {
    super.initState();
  }

  void setChartData() {
    List<KLineEntity>? res = [];
    for (var item in exampleData) {
      res.add(KLineEntity.fromJson(item));
    }
    setState(() {
      data = res;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: ElevatedButton(onPressed: () {
          setChartData();
        }, child: const Text('绘制数据'),),
        title: const Text('K Line'),
        centerTitle: true,
      ),
      body: Container(
        width: 1080.w,
        height: 2400.h,
        color: Colors.white,
        child: KChartWidget(
          data,
          chartStyle,
          chartColors,
          isTrendLine: true,
          isTapShowInfoDialog: true,
          isLine: false,
          hideGrid: false,
          mainState: mainState,
        ),
      ),
    );
  }
}

**Comment by mafanwei** [comment]
flutter版本是什么呢
ios版本是什么呢

**Comment by edison-fe-html** [comment]
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (5 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

xcode: Version 14.3 (14E222b)
Ios: 15.4.1

**Comment by mafanwei** [comment]
好的，我抽空run一下看看。

**Comment by edison-fe-html** [comment]
ok  麻烦您看一下

**Comment by mafanwei** [comment]
我用了
ios16.4.1
flutter 3.7.5
master分支
使用内置json数据
浏览器可以正常绘制

**Comment by edison-fe-html** [comment]
那您试下接口的数据呢

**Comment by edison-fe-html** [comment]
我发现这个问题的原因是因为pc上的web渲染是使用canvaskit  而在移动端上面使用的是html渲染 所以导致出现问题 我切换成强制使用canvaskit渲染之后everything is ok  但是我并不清楚强制使用canvaskit会不会带来一些其他得影响

**Comment by mafanwei** [comment]
看起来像是flutter的系统兼容bug，应该和项目无关
