### ISSUE TITLE
折线图粗细不一致

### ISSUE THREAD

**Issue by typ0520** [OpenFlutter/k_chart#8]
应该是对画布进行了缩放导致的，具体表现是，横线宽度是正常的(画笔对应的strokeWidth)，缩小状态下竖线明显细很多，请问下这个问题有解决办法吗

![1596698673078](https://user-images.githubusercontent.com/4417749/89503331-f75ab680-d7f8-11ea-9be0-924a98ec311e.jpg)

**Comment by typ0520** [comment]
缩放建议不要直接对画布进行缩放，改变pointWidth的值更合理些，目前这种方式往上面画图标等等这种操作，都会导致x轴被缩放

**Comment by mafanwei** [comment]
根据缩放乘以一个对应的比例就可以了，欢迎pr

**Comment by typ0520** [comment]
图片可以根据缩放级别进行相应的缩放，不过折线图就不行了

**Comment by mafanwei** [comment]
我想了一下，可能先缩放，然后画折线图，可以解决这个问题

**Comment by mafanwei** [comment]
hi，有什么进展？

**Comment by typ0520** [comment]
参考你的代码重写了一套，缩放针对单跟k线做，里面绑定了一些公司的业务逻辑，暂时没法提交pr

**Comment by mafanwei** [comment]
我修改了一些内容，目测这个问题很不明显了。
