### ISSUE TITLE
Example android app

### ISSUE THREAD

**Issue by armanTabib** [OpenFlutter/k_chart#81]
I'm trying to import this view in native android application and I'm not familiar with flutter. 
How should I do it?

**Comment by mafanwei** [comment]
Here are the steps on how to import Flutter view to your native Android app:

Add Flutter SDK as a dependency to your Android project.
Create a Flutter module.
Write a view in your Flutter module.
Use Flutter view in your Android project.
Here are more detailed steps:

Add Flutter SDK as a dependency to your Android project. You can find instructions on how to add Flutter SDK in the Flutter documentation: https://docs.flutter.dev/get-started/install.
Create a Flutter module. You can find instructions on how to create a Flutter module in the Flutter documentation: https://docs.flutter.dev/development/add-to-app/android/project-setup.
Write a view in your Flutter module. You can find instructions on how to write a Flutter view in the Flutter documentation: https://docs.flutter.dev/development/ui/widgets.
Use Flutter view in your Android project. You can find instructions on how to use Flutter view in your Android project in the Flutter documentation: https://docs.flutter.dev/development/add-to-app/android/add-flutter-screen.
If you are not familiar with Flutter, I recommend that you read the Flutter documentation first to learn about the basic concepts of Flutter. Then, you can follow the steps above to import Flutter view to your native Android app.

You can also ask AI for more detailed assistance.

**Comment by armanTabib** [comment]
The flutter documentation did not much help for me. Though I managed to do what I wanted, and now I'm just looking for a free time to post it here for other people to use if necessary .
Thank you
