### ISSUE TITLE
Candle chart is overflow than right price pannel

### ISSUE THREAD

**Issue by frankie060392** [OpenFlutter/k_chart#9]
Sorry for my bad english. Please help me how to set right padding for candle chart.

**Comment by mafanwei** [comment]
try padding chart,not support padding a part

**Comment by mafanwei** [comment]
It's easily expandable so you can make your own. pr is welcome.

**Comment by mafanwei** [comment]
Can you provide pictures？Waiting for your response. Maybe see #1

**Comment by mafanwei** [comment]
no response. closed
